name = "fiestabacktothe80s"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
keep_vars = true

[
vars
]
NEXT_PUBLIC_PUBLIC_URL="https://www.fiestabacktothe80s.com.ar"
NEXT_PUBLIC_ASSETS_URL="/assets"
NEXT_PUBLIC_API_SERVERLESS_URL="https://api.fiestabacktothe80s.workers.dev"
NEXT_PUBLIC_API_SERVERLESS_AUTH="0dd2ad3950601fff49205b7b153c35bd"
NEXT_PUBLIC_API_ROUTES_SERVERLESS_IMAGES_URL="/images"
