/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ObjectApiRequest"];
                    "text/json": components["schemas"]["ObjectApiRequest"];
                    "application/*+json": components["schemas"]["ObjectApiRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ObjectStringObjectApiResponse"];
                        "application/json": components["schemas"]["ObjectStringObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectStringObjectApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ObjectStringObjectApiResponse"];
                        "application/json": components["schemas"]["ObjectStringObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectStringObjectApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ObjectApiRequest: {
            data?: unknown;
        };
        ObjectObjectResponseData: {
            data?: unknown;
            message?: string | null;
            reference?: unknown;
        };
        ObjectStringObjectApiResponse: {
            /** Format: int32 */
            code?: number;
            response?: components["schemas"]["ObjectObjectResponseData"];
            error?: components["schemas"]["StringObjectResponseData"];
            reference?: unknown;
        };
        StringObjectResponseData: {
            data?: string | null;
            message?: string | null;
            reference?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
