name: Deploy Client (Cloudflare Page)

on:
  push:
    branches: [main, master]
    paths:
      - "client/**"
      - "shared/**"
      - ".github/workflows/client.yml"

jobs:
  deploy:
    if: github.repository != 'diegoev26/template'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci --legacy-peer-deps

      - name: Compilar paquete Shared
        run: npm run build:shared

      - name: Compilar paquete Client
        run: npm run build:client

      - name: Desplegar en Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: "client/out"
